{
 "title": "Archiver",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "UP time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds { service = \"archiver\" }"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads { service = \"archiver\" }",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{ service = \"archiver\" }",
     "legendFormat": "process cpu usage"
    },
    {
     "expr": "system_cpu_usage{ service = \"archiver\" }",
     "legendFormat": "system cpu usage"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{ area = \"heap\", service = \"archiver\" }"
    }
   ]
  },
  {
   "title": "GC pause",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_max{ service = \"archiver\" }",
     "legendFormat": "{{ cause }} - {{ format }}"
    }
   ]
  },
  {
   "title": "Saved object locations - listener",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "object_location_source_listener_saved{ service = \"archiver\" }"
    }
   ]
  },
  {
   "title": "Save object locations count - listener",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(object_location_source_listener_saved{ service = \"archiver\" }[1m])",
     "legendFormat": "object locations/s"
    }
   ]
  },
  {
   "title": "Save object locations time - listener",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(object_location_source_listener_time_seconds_sum{ service = \"archiver\" }[5m])) / sum(rate(object_location_source_listener_time_seconds_count{ service = \"archiver\" }[5m]))",
     "legendFormat": "Operation time"
    }
   ]
  },
  {
   "title": "Save object locations - DB query count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(object_location_query_save_count{ service = \"archiver\" }[1m])",
     "legendFormat": "query/s"
    }
   ]
  },
  {
   "title": "Save object locations - DB query time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(object_location_query_save_time_seconds_sum{ service = \"archiver\" }[5m])) / sum(rate(object_location_query_save_time_seconds_count{ service = \"archiver\" }[5m]))",
     "legendFormat": "query time"
    }
   ]
  },
  {
   "title": "Find object location - DB query count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(object_location_query_find_count{ service = \"archiver\" }[1m])",
     "legendFormat": "query/s"
    }
   ]
  },
  {
   "title": "Find object location - DB query time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(object_location_query_find_time_seconds_sum{ service = \"archiver\" }[5m])) / sum(rate(object_location_query_find_time_seconds_count{ service = \"archiver\" }[5m]))",
     "legendFormat": "query time"
    }
   ]
  }
 ]
}