{
 "title": "Performer",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "UP time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds { service = \"performer\" }"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads { service = \"performer\" }",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{ service = \"performer\" }",
     "legendFormat": "process cpu usage"
    },
    {
     "expr": "system_cpu_usage{ service = \"performer\" }",
     "legendFormat": "system cpu usage"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{ area = \"heap\", service = \"performer\" }"
    }
   ]
  },
  {
   "title": "GC pause",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_max{ service = \"performer\" }",
     "legendFormat": "{{ cause }} - {{ format }}"
    }
   ]
  },
  {
   "title": "Location snapshot - Job execution count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "location_snapshot_job_count{ service = \"performer\" }"
    }
   ]
  },
  {
   "title": "Location snapshot  - Job execution time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(location_snapshot_job_time_seconds_sum{ service = \"performer\" }[1m])) / sum(rate(location_snapshot_job_time_seconds_count{ service = \"performer\" }[1m]))",
     "legendFormat": "query time"
    }
   ]
  }
 ]
}