version: '3.6'
networks:
  location-tracker-net:
services:
  archiver:
    image: dsniatecki/archiver:0.0.2
    container_name: archiver
    environment:
      DB_NAME: archiver
      DB_USER: archiver
      DB_PASSWORD: archiver
      SPRING_R2DBC_URL: r2dbc:postgresql://archiver-db:5432/archiver
      SPRING_FLYWAY_URL: jdbc:postgresql://archiver-db:5432/archiver
      SPRING_RABBITMQ_HOST: archiver-msg-broker
      SPRING_RABBITMQ_USERNAME: archiver
      SPRING_RABBITMQ_PASSWORD: archiver
      SPRING_RABBITMQ_VIRTUAL_HOST: location-tracker
      SPRING_RABBITMQ_OBJECT_LOCATION_SOURCE_QUEUE: archiver.object.location.source.queue
      SPRING_RABBITMQ_OBJECT_LOCATION_REQUEST_QUEUE: archiver.object.location.request.queue
      SPRING_RABBITMQ_SSL_ENABLED: 'false'
    ports:
      - '10030:8080'
    networks:
      - location-tracker-net
    depends_on:
      - archiver-db
      - archiver-msg-broker
  archiver-db:
    image: timescale/timescaledb:2.6.0-pg14
    container_name: archiver-db
    environment:
      POSTGRES_USER: archiver
      POSTGRES_PASSWORD: archiver
      POSTGRES_DB: archiver
    ports:
      - '11030:5432'
    networks:
      - location-tracker-net
  archiver-msg-broker:
    image: rabbitmq:3.9.8-management-alpine
    container_name: archiver-msg-broker
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_management load_definitions '/tmp/definitions.json'"
    volumes:
      - ./archiver/src/test/resources/rabbitmq-test-definitions.json:/tmp/definitions.json
    ports:
      - '5671:5671'
      - '5672:5672'
      - '15672:15672'
    networks:
      - location-tracker-net
  receiver:
    image: dsniatecki/receiver:0.0.2
    container_name: receiver
    environment:
      SPRING_RABBITMQ_HOST: archiver-msg-broker
      SPRING_RABBITMQ_USERNAME: archiver
      SPRING_RABBITMQ_PASSWORD: archiver
      SPRING_RABBITMQ_VIRTUAL_HOST: location-tracker
      SPRING_RABBITMQ_OBJECT_LOCATION_EXCHANGE: archiver.exchange
      SPRING_RABBITMQ_OBJECT_LOCATION_STORE_ROUTING_KEY: archiver-object-location-source
      SPRING_RABBITMQ_SSL_ENABLED: 'false'
    ports:
      - '10020:8080'
    networks:
      - location-tracker-net
    depends_on:
      - archiver
  storage:
    image: dsniatecki/storage:0.0.2
    container_name: storage
    environment:
      DB_NAME: storage
      DB_USER: storage
      DB_PASSWORD: storage
      SPRING_R2DBC_URL: r2dbc:postgresql://storage-db:5432/storage
      SPRING_FLYWAY_URL: jdbc:postgresql://storage-db:5432/storage
    ports:
      - '10010:8080'
    networks:
      - location-tracker-net
    depends_on:
      - storage-db
  storage-db:
    image: postgres:14-alpine
    container_name: storage-db
    environment:
      POSTGRES_USER: storage
      POSTGRES_PASSWORD: storage
      POSTGRES_DB: storage
    ports:
      - '11010:5432'
    networks:
      - location-tracker-net
  performer:
    image: dsniatecki/performer:0.0.2
    container_name: performer
    environment:
      PERFORMER_STORAGE_BASE_PATH: 'http://storage:8080/api'
      PERFORMER_ARCHIVER_BASE_PATH: 'http://archiver:8080/api'
      PERFORMER_JOBS_LOCATION_SNAPSHOT_SCHEDULER_CRON: '1 * * * * *'
      PERFORMER_JOBS_LOCATION_SNAPSHOT_TOLERANCE: '24h'
      PERFORMER_JOBS_LOCATION_SNAPSHOT_SFTP_HOST: 'sftp-server'
      PERFORMER_JOBS_LOCATION_SNAPSHOT_SFTP_PORT: 22
      PERFORMER_JOBS_LOCATION_SNAPSHOT_SFTP_USER: 'performer'
      PERFORMER_JOBS_LOCATION_SNAPSHOT_SFTP_PASSWORD: 'performer'
      PERFORMER_JOBS_LOCATION_SNAPSHOT_SFTP_PATH: 'upload'
    ports:
      - '10040:8080'
    networks:
      - location-tracker-net
    depends_on:
      - sftp-server
      - storage
      - archiver
  proxy:
    image: dsniatecki/proxy:0.0.2
    container_name: proxy
    volumes:
      - ./utils/proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./visualizer/dist/visualizer:/usr/share/nginx/html
    ports:
      - '8000:80'
    networks:
      - location-tracker-net
    depends_on:
      - storage
      - receiver
      - archiver
      - grafana
  alert-manager:
    image: prom/alertmanager:v0.23.0
    container_name: alert-manager
    command: --config.file=/config/alertmanager.yml --log.level=info
    volumes:
      - ./utils/alertmanager/alertmanager.yml:/config/alertmanager.yml
    ports:
      - '11193:9093'
    networks:
      - location-tracker-net
    depends_on:
      - prometheus
  grafana:
    image: grafana/grafana:8.2.6
    container_name: grafana
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: '/var/lib/grafana/dashboards/archiver_dashboard.json'
      GF_SERVER_ROOT_URL: '%(protocol)s://%(domain)s:/grafana'
    volumes:
      - ./utils/grafana/provisioning:/etc/grafana/provisioning
      - ./utils/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - '11000:3000'
    networks:
      - location-tracker-net
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus:v2.33.3
    container_name: prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --log.level=info
    volumes:
      - ./utils/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./utils/prometheus/alerts.yml:/etc/prometheus/alerts.yml
    ports:
      - '11190:9090'
    networks:
      - location-tracker-net
  sftp-server:
    image: atmoz/sftp:alpine
    command: performer:performer:1001
    container_name: sftp-server
    volumes:
      - ./sftp-store:/home/performer/upload
    ports:
      - '11022:22'
    networks:
      - location-tracker-net
  smtp-server:
    image: mailhog/mailhog:v1.0.1
    container_name: smtp-server
    ports:
      - '11025:1025'
      - '11005:8025'
    networks:
      - location-tracker-net

