version: '3.6'
networks:
  location-tracker-net:
volumes:
  grafana-storage:
services:
  receiver:
    build:
      context: receiver
    container_name: receiver
    environment:
      SPRING_RABBITMQ_HOST: archiver-msg-broker
      SPRING_RABBITMQ_USERNAME: archiver
      SPRING_RABBITMQ_PASSWORD: archiver
      SPRING_RABBITMQ_VIRTUAL_HOST: location-tracker
      SPRING_RABBITMQ_OBJECT_LOCATION_EXCHANGE: archiver.exchange
      SPRING_RABBITMQ_OBJECT_LOCATION_STORE_ROUTING_KEY: archiver-object-location-source
      SPRING_RABBITMQ_SSL_ENABLED: "false"
#      DEVELOPMENT_MODE: "true"
#      APP_LOGGING_LEVEL: DEBUG
    ports:
      - "8080:8080"
    networks:
      - location-tracker-net
    depends_on:
      - archiver
  archiver:
    build:
      context: archiver
    container_name: archiver
    environment:
      DB_NAME: archiver
      DB_USER: archiver
      DB_PASSWORD: archiver
      SPRING_R2DBC_URL: r2dbc:postgresql://archiver-db:5432/archiver
      SPRING_FLYWAY_URL: jdbc:postgresql://archiver-db:5432/archiver
      SPRING_RABBITMQ_HOST: archiver-msg-broker
      SPRING_RABBITMQ_USERNAME: archiver
      SPRING_RABBITMQ_PASSWORD: archiver
      SPRING_RABBITMQ_VIRTUAL_HOST: location-tracker
      SPRING_RABBITMQ_OBJECT_LOCATION_SOURCE_QUEUE: archiver.object.location.source.queue
      SPRING_RABBITMQ_OBJECT_LOCATION_REQUEST_QUEUE: archiver.object.location.request.queue
      SPRING_RABBITMQ_SSL_ENABLED: "false"
#      DEVELOPMENT_MODE: "true"
#      APP_LOGGING_LEVEL: DEBUG
    ports:
      - "8090:8080"
    networks:
      - location-tracker-net
    depends_on:
      - archiver-db
      - archiver-msg-broker
  archiver-db:
    image: timescale/timescaledb:2.5.1-pg14
    container_name: archiver-db
    environment:
      POSTGRES_USER: archiver
      POSTGRES_PASSWORD: archiver
      POSTGRES_DB: archiver
    ports:
      - "5432:5432"
    networks:
      - location-tracker-net
  archiver-msg-broker:
    image: rabbitmq:3.9.8-management-alpine
    container_name: archiver-msg-broker
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: '-rabbitmq_management load_definitions "/tmp/definitions.json"'
    volumes:
      - ./archiver/src/test/resources/rabbitmq-test-definitions.json:/tmp/definitions.json
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
    networks:
      - location-tracker-net
  prometheus:
    image: prom/prometheus:v2.33.3
    container_name: prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --log.level=debug
    volumes:
      - ./utils/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - location-tracker-net
    depends_on:
      - receiver
  grafana:
    image: grafana:latest
    container_name: grafana
    build:
      context: utils/grafana
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/var/lib/grafana/dashboards/archiver_dashboard.json"
    ports:
      - "3000:3000"
    networks:
      - location-tracker-net
    depends_on:
      - receiver

