version: '3.6'
networks:
  location-tracker-net:
services:
  storage:
    build:
      context: .
    container_name: storage
    environment:
      GUARD_CERT_URI: "http:// <<HOST-IP>> :11050/realms/location-tracker/protocol/openid-connect/certs"
      DB_HOST: storage-db
      DB_NAME: storage
      DB_USER: storage
      DB_PASSWORD: storage
    # DEVELOPMENT_MODE: "true"
    # APP_LOGGING_LEVEL: DEBUG
    ports:
      - "10010:8080"
    networks:
      - location-tracker-net
    depends_on:
      - storage-db
  storage-db:
    image: postgres:14-alpine
    container_name: storage-db
    environment:
      POSTGRES_USER: storage
      POSTGRES_PASSWORD: storage
      POSTGRES_DB: storage
    ports:
      - "11010:5432"
    networks:
      - location-tracker-net