receiver:
  time-zone-id: "UTC"

guard:
  cert-uri: "#{null}"
  public-key-location: "#{null}"

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: "${guard.public-key-location}"
          jwk-set-uri: "${guard.cert-uri}"
  rabbitmq:
    address-shuffle-mode: random
    host: ""
    password: ""
    username: ""
    virtual-host: ""
    object-location:
      exchange: ""
      store:
        routing-key:
        pool-size: 4
        batch-size: 250
        buffer-limit: 10000
        timeout-millis: 1000
    dynamic: false
    ssl:
      enabled: true

management:
  endpoint:
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "info, metrics, prometheus, health"
