storage:
  time-zone-id: "UTC"
  tolerance: "24h"

db:
  host: ""
  port: 5432
  name: ""
  user: ""
  password: ""

spring:
  r2dbc:
    url: "r2dbc:postgresql://${db.host}:${db.port}/${db.name}?ssl=true&sslMode=require"
    username: "${db.user}"
    password: "${db.password}"
  flyway:
    url: "jdbc:postgresql://${db.host}:${db.port}/${db.name}?ssl=true&sslmode=require"
    user: "${db.user}"
    password: "${db.password}"
    locations: classpath:db

management:
  endpoint:
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "info, metrics, prometheus, health"
